// Example NFT Contract ABI - Replace with your actual ABI
export const STAR_KEEPER = [
	{
		inputs: [
			{ internalType: "string", name: "_name", type: "string" },
			{ internalType: "string", name: "_symbol", type: "string" },
			{ internalType: "uint256", name: "_maxSupply", type: "uint256" },
			{ internalType: "uint256", name: "_mintPrice", type: "uint256" },
			{
				internalType: "uint256",
				name: "_tokenMintPrice",
				type: "uint256",
			},
			{ internalType: "address", name: "_paymentToken", type: "address" },
			{ internalType: "string", name: "_baseTokenURI", type: "string" },
			{
				internalType: "string",
				name: "_collectionImageURI",
				type: "string",
			},
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], type: "error", name: "ERC20PaymentNotEnabled" },
	{
		inputs: [],
		type: "error",
		name: "ERC721EnumerableForbiddenBatchMint",
	},
	{
		inputs: [
			{ internalType: "address", name: "sender", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "address", name: "owner", type: "address" },
		],
		type: "error",
		name: "ERC721IncorrectOwner",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		type: "error",
		name: "ERC721InsufficientApproval",
	},
	{
		inputs: [{ internalType: "address", name: "approver", type: "address" }],
		type: "error",
		name: "ERC721InvalidApprover",
	},
	{
		inputs: [{ internalType: "address", name: "operator", type: "address" }],
		type: "error",
		name: "ERC721InvalidOperator",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		type: "error",
		name: "ERC721InvalidOwner",
	},
	{
		inputs: [{ internalType: "address", name: "receiver", type: "address" }],
		type: "error",
		name: "ERC721InvalidReceiver",
	},
	{
		inputs: [{ internalType: "address", name: "sender", type: "address" }],
		type: "error",
		name: "ERC721InvalidSender",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		type: "error",
		name: "ERC721NonexistentToken",
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "uint256", name: "index", type: "uint256" },
		],
		type: "error",
		name: "ERC721OutOfBoundsIndex",
	},
	{ inputs: [], type: "error", name: "InsufficientPayment" },
	{ inputs: [], type: "error", name: "InvalidAddress" },
	{ inputs: [], type: "error", name: "InvalidMaxSupply" },
	{ inputs: [], type: "error", name: "MaxSupplyReached" },
	{ inputs: [], type: "error", name: "OnlyFactoryAllowed" },
	{ inputs: [], type: "error", name: "TokenDoesNotExist" },
	{ inputs: [], type: "error", name: "TokenTransferFailed" },
	{ inputs: [], type: "error", name: "WithdrawalFailed" },
	{
		inputs: [
			{
				internalType: "address",
				name: "owner",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "approved",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
		],
		type: "event",
		name: "Approval",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "owner",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "operator",
				type: "address",
				indexed: true,
			},
			{
				internalType: "bool",
				name: "approved",
				type: "bool",
				indexed: false,
			},
		],
		type: "event",
		name: "ApprovalForAll",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "string",
				name: "newURI",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "BaseURIUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "string",
				name: "newURI",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "CollectionImageURIUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "amount",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "FundsWithdrawn",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "newMaxSupply",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "MaxSupplyUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "MintPriceUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
			{
				internalType: "string",
				name: "paymentMethod",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "Minted",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "newToken",
				type: "address",
				indexed: false,
			},
		],
		type: "event",
		name: "PaymentTokenUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "TokenMintPriceUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "amount",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "TokensWithdrawn",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "from",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
		],
		type: "event",
		name: "Transfer",
		anonymous: false,
	},
	{
		inputs: [
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "approve",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		stateMutability: "view",
		type: "function",
		name: "balanceOf",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "baseTokenURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "collectionImageURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "factory",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "getApproved",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "getCollectionInfo",
		outputs: [
			{ internalType: "string", name: "name_", type: "string" },
			{ internalType: "string", name: "symbol_", type: "string" },
			{ internalType: "uint256", name: "totalSupply_", type: "uint256" },
			{ internalType: "uint256", name: "maxSupply_", type: "uint256" },
			{ internalType: "uint256", name: "mintPrice_", type: "uint256" },
			{
				internalType: "uint256",
				name: "tokenMintPrice_",
				type: "uint256",
			},
			{ internalType: "address", name: "paymentToken_", type: "address" },
		],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "getCurrentSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "address", name: "operator", type: "address" },
		],
		stateMutability: "view",
		type: "function",
		name: "isApprovedForAll",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "maxSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "payable",
		type: "function",
		name: "mint",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "mintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "address", name: "_to", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "mintTo",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "nonpayable",
		type: "function",
		name: "mintWithToken",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "name",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "ownerOf",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "paymentToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "safeTransferFrom",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "bytes", name: "data", type: "bytes" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "safeTransferFrom",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "bool", name: "approved", type: "bool" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "setApprovalForAll",
	},
	{
		inputs: [{ internalType: "string", name: "_newBaseURI", type: "string" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setBaseURI",
	},
	{
		inputs: [{ internalType: "string", name: "_newImageURI", type: "string" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setCollectionImageURI",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "_newMaxSupply", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "setMaxSupply",
	},
	{
		inputs: [{ internalType: "uint256", name: "_newPrice", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setMintPrice",
	},
	{
		inputs: [{ internalType: "address", name: "_newToken", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setPaymentToken",
	},
	{
		inputs: [{ internalType: "uint256", name: "_newPrice", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setTokenMintPrice",
	},
	{
		inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
		stateMutability: "view",
		type: "function",
		name: "supportsInterface",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "symbol",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "tokenByIndex",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "tokenMintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "uint256", name: "index", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
		name: "tokenOfOwnerByIndex",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "tokenURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "totalSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "transferFrom",
	},
	{
		inputs: [
			{ internalType: "address payable", name: "_to", type: "address" },
			{ internalType: "uint256", name: "_amount", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "withdrawFunds",
	},
	{
		inputs: [{ internalType: "address", name: "_to", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "withdrawTokens",
	},
] as const;

// Example Token Contract ABI - Replace with your actual ABI
export const STAR_KEEPER_FACTORY = [
	{
		inputs: [],
		name: "totalSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "account", type: "address" }],
		name: "balanceOf",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
] as const;

export const STAR_OWNER = [
	{
		inputs: [
			{ internalType: "string", name: "_name", type: "string" },
			{ internalType: "string", name: "_symbol", type: "string" },
			{ internalType: "uint256", name: "_mintPrice", type: "uint256" },
			{
				internalType: "uint256",
				name: "_tokenMintPrice",
				type: "uint256",
			},
			{ internalType: "address", name: "_paymentToken", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], type: "error", name: "AccessControlBadConfirmation" },
	{
		inputs: [
			{ internalType: "address", name: "account", type: "address" },
			{ internalType: "bytes32", name: "neededRole", type: "bytes32" },
		],
		type: "error",
		name: "AccessControlUnauthorizedAccount",
	},
	{ inputs: [], type: "error", name: "AdminAlreadyExists" },
	{ inputs: [], type: "error", name: "AdminDoesNotExist" },
	{ inputs: [], type: "error", name: "AlreadyVoted" },
	{ inputs: [], type: "error", name: "ERC20PaymentNotEnabled" },
	{
		inputs: [],
		type: "error",
		name: "ERC721EnumerableForbiddenBatchMint",
	},
	{
		inputs: [
			{ internalType: "address", name: "sender", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "address", name: "owner", type: "address" },
		],
		type: "error",
		name: "ERC721IncorrectOwner",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		type: "error",
		name: "ERC721InsufficientApproval",
	},
	{
		inputs: [{ internalType: "address", name: "approver", type: "address" }],
		type: "error",
		name: "ERC721InvalidApprover",
	},
	{
		inputs: [{ internalType: "address", name: "operator", type: "address" }],
		type: "error",
		name: "ERC721InvalidOperator",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		type: "error",
		name: "ERC721InvalidOwner",
	},
	{
		inputs: [{ internalType: "address", name: "receiver", type: "address" }],
		type: "error",
		name: "ERC721InvalidReceiver",
	},
	{
		inputs: [{ internalType: "address", name: "sender", type: "address" }],
		type: "error",
		name: "ERC721InvalidSender",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		type: "error",
		name: "ERC721NonexistentToken",
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "uint256", name: "index", type: "uint256" },
		],
		type: "error",
		name: "ERC721OutOfBoundsIndex",
	},
	{ inputs: [], type: "error", name: "InsufficientPayment" },
	{ inputs: [], type: "error", name: "InvalidAddress" },
	{ inputs: [], type: "error", name: "InvalidParameters" },
	{ inputs: [], type: "error", name: "LastAdminCannotBeRemoved" },
	{ inputs: [], type: "error", name: "ProposalAlreadyExecuted" },
	{ inputs: [], type: "error", name: "ProposalExpired" },
	{ inputs: [], type: "error", name: "ProposalNotFound" },
	{ inputs: [], type: "error", name: "QuorumNotReached" },
	{ inputs: [], type: "error", name: "TokenTransferFailed" },
	{ inputs: [], type: "error", name: "WithdrawalFailed" },
	{
		inputs: [
			{
				internalType: "address",
				name: "admin",
				type: "address",
				indexed: true,
			},
		],
		type: "event",
		name: "AdminAdded",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "admin",
				type: "address",
				indexed: true,
			},
		],
		type: "event",
		name: "AdminRemoved",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "owner",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "approved",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
		],
		type: "event",
		name: "Approval",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "owner",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "operator",
				type: "address",
				indexed: true,
			},
			{
				internalType: "bool",
				name: "approved",
				type: "bool",
				indexed: false,
			},
		],
		type: "event",
		name: "ApprovalForAll",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "amount",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "FundsWithdrawn",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "MintPriceUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "newToken",
				type: "address",
				indexed: false,
			},
		],
		type: "event",
		name: "PaymentTokenUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "proposalId",
				type: "uint256",
				indexed: true,
			},
			{
				internalType: "enum StarOwner.ProposalType",
				name: "proposalType",
				type: "uint8",
				indexed: false,
			},
			{
				internalType: "address",
				name: "proposer",
				type: "address",
				indexed: true,
			},
		],
		type: "event",
		name: "ProposalCreated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "proposalId",
				type: "uint256",
				indexed: true,
			},
			{
				internalType: "enum StarOwner.ProposalType",
				name: "proposalType",
				type: "uint8",
				indexed: false,
			},
		],
		type: "event",
		name: "ProposalExecuted",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "proposalId",
				type: "uint256",
				indexed: true,
			},
			{
				internalType: "address",
				name: "voter",
				type: "address",
				indexed: true,
			},
		],
		type: "event",
		name: "ProposalVoted",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "newThreshold",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "QuorumUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "bytes32",
				name: "role",
				type: "bytes32",
				indexed: true,
			},
			{
				internalType: "bytes32",
				name: "previousAdminRole",
				type: "bytes32",
				indexed: true,
			},
			{
				internalType: "bytes32",
				name: "newAdminRole",
				type: "bytes32",
				indexed: true,
			},
		],
		type: "event",
		name: "RoleAdminChanged",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "bytes32",
				name: "role",
				type: "bytes32",
				indexed: true,
			},
			{
				internalType: "address",
				name: "account",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "sender",
				type: "address",
				indexed: true,
			},
		],
		type: "event",
		name: "RoleGranted",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "bytes32",
				name: "role",
				type: "bytes32",
				indexed: true,
			},
			{
				internalType: "address",
				name: "account",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "sender",
				type: "address",
				indexed: true,
			},
		],
		type: "event",
		name: "RoleRevoked",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "TokenMintPriceUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
			{
				internalType: "string",
				name: "paymentMethod",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "TokenMinted",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: false,
			},
			{
				internalType: "string",
				name: "newURI",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "TokenURIUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "amount",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "TokensWithdrawn",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "from",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
		],
		type: "event",
		name: "Transfer",
		anonymous: false,
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "DEFAULT_ADMIN_ROLE",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "approve",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		stateMutability: "view",
		type: "function",
		name: "balanceOf",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "address", name: "_admin", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "createAddAdminProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "address", name: "_admin", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "createRemoveAdminProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "_newPrice", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "createSetMintPriceProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "address", name: "_newToken", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "createSetPaymentTokenProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "_newFee", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "createSetTokenFeeProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "_to", type: "address" },
			{ internalType: "uint256", name: "_amount", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "createWithdrawFundsProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "address", name: "_to", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "createWithdrawTokensProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "getAdmins",
		outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "getApproved",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "getContractInfo",
		outputs: [
			{ internalType: "string", name: "name_", type: "string" },
			{ internalType: "string", name: "symbol_", type: "string" },
			{ internalType: "uint256", name: "totalSupply_", type: "uint256" },
			{ internalType: "uint256", name: "mintPrice_", type: "uint256" },
			{
				internalType: "uint256",
				name: "tokenMintPrice_",
				type: "uint256",
			},
			{ internalType: "address", name: "paymentToken_", type: "address" },
			{
				internalType: "uint256",
				name: "quorumThreshold_",
				type: "uint256",
			},
			{
				internalType: "uint256",
				name: "totalProposals_",
				type: "uint256",
			},
		],
	},
	{
		inputs: [{ internalType: "uint256", name: "_proposalId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "getProposalDetails",
		outputs: [
			{ internalType: "address", name: "proposer", type: "address" },
			{ internalType: "uint256", name: "createdAt", type: "uint256" },
			{ internalType: "uint256", name: "approvalCount", type: "uint256" },
			{
				internalType: "uint256",
				name: "expirationTime",
				type: "uint256",
			},
			{ internalType: "bool", name: "executed", type: "bool" },
			{
				internalType: "enum StarOwner.ProposalType",
				name: "proposalType",
				type: "uint8",
			},
			{ internalType: "address", name: "targetAddress", type: "address" },
			{ internalType: "uint256", name: "value", type: "uint256" },
		],
	},
	{
		inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
		name: "getRoleAdmin",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "getTotalProposals",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{ internalType: "address", name: "account", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "grantRole",
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{ internalType: "address", name: "account", type: "address" },
		],
		stateMutability: "view",
		type: "function",
		name: "hasRole",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [
			{ internalType: "uint256", name: "_proposalId", type: "uint256" },
			{ internalType: "address", name: "_admin", type: "address" },
		],
		stateMutability: "view",
		type: "function",
		name: "hasVotedForProposal",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "address", name: "operator", type: "address" },
		],
		stateMutability: "view",
		type: "function",
		name: "isApprovedForAll",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [{ internalType: "string", name: "ipfsURI", type: "string" }],
		stateMutability: "payable",
		type: "function",
		name: "mint",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "mintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "string", name: "ipfsURI", type: "string" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "mintWithToken",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "name",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "ownerOf",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "paymentToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "quorumThreshold",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{
				internalType: "address",
				name: "callerConfirmation",
				type: "address",
			},
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "renounceRole",
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{ internalType: "address", name: "account", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "revokeRole",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "safeTransferFrom",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "bytes", name: "data", type: "bytes" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "safeTransferFrom",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "bool", name: "approved", type: "bool" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "setApprovalForAll",
	},
	{
		inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
		stateMutability: "view",
		type: "function",
		name: "supportsInterface",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "symbol",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "tokenByIndex",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "tokenMintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "uint256", name: "index", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
		name: "tokenOfOwnerByIndex",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "tokenURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "totalSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "transferFrom",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "string", name: "newURI", type: "string" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "updateTokenURI",
	},
	{
		inputs: [{ internalType: "uint256", name: "_proposalId", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "voteForProposal",
	},
] as const;
