export const STAR_KEEPER = [
	{
		inputs: [
			{ internalType: "string", name: "name_", type: "string" },
			{ internalType: "string", name: "symbol_", type: "string" },
			{ internalType: "uint256", name: "maxSupply_", type: "uint256" },
			{ internalType: "uint256", name: "mintPrice_", type: "uint256" },
			{
				internalType: "uint256",
				name: "tokenMintPrice_",
				type: "uint256",
			},
			{ internalType: "address", name: "paymentToken_", type: "address" },
			{ internalType: "string", name: "baseTokenURI_", type: "string" },
			{
				internalType: "string",
				name: "collectionImageURI_",
				type: "string",
			},
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], type: "error", name: "ERC20PaymentNotEnabled" },
	{
		inputs: [],
		type: "error",
		name: "ERC721EnumerableForbiddenBatchMint",
	},
	{
		inputs: [
			{ internalType: "address", name: "sender", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "address", name: "owner", type: "address" },
		],
		type: "error",
		name: "ERC721IncorrectOwner",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		type: "error",
		name: "ERC721InsufficientApproval",
	},
	{
		inputs: [{ internalType: "address", name: "approver", type: "address" }],
		type: "error",
		name: "ERC721InvalidApprover",
	},
	{
		inputs: [{ internalType: "address", name: "operator", type: "address" }],
		type: "error",
		name: "ERC721InvalidOperator",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		type: "error",
		name: "ERC721InvalidOwner",
	},
	{
		inputs: [{ internalType: "address", name: "receiver", type: "address" }],
		type: "error",
		name: "ERC721InvalidReceiver",
	},
	{
		inputs: [{ internalType: "address", name: "sender", type: "address" }],
		type: "error",
		name: "ERC721InvalidSender",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		type: "error",
		name: "ERC721NonexistentToken",
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "uint256", name: "index", type: "uint256" },
		],
		type: "error",
		name: "ERC721OutOfBoundsIndex",
	},
	{ inputs: [], type: "error", name: "InsufficientBalance" },
	{ inputs: [], type: "error", name: "InsufficientPayment" },
	{ inputs: [], type: "error", name: "InvalidAddress" },
	{ inputs: [], type: "error", name: "InvalidBaseURI" },
	{ inputs: [], type: "error", name: "InvalidImageURI" },
	{ inputs: [], type: "error", name: "InvalidMaxSupply" },
	{ inputs: [], type: "error", name: "InvalidParameters" },
	{ inputs: [], type: "error", name: "MaxSupplyReached" },
	{ inputs: [], type: "error", name: "OnlyFactoryAllowed" },
	{
		inputs: [{ internalType: "address", name: "token", type: "address" }],
		type: "error",
		name: "SafeERC20FailedOperation",
	},
	{ inputs: [], type: "error", name: "SupplyTooLow" },
	{ inputs: [], type: "error", name: "TokenDoesNotExist" },
	{ inputs: [], type: "error", name: "TokenTransferFailed" },
	{ inputs: [], type: "error", name: "WithdrawalFailed" },
	{
		inputs: [
			{
				internalType: "address",
				name: "owner",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "approved",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
		],
		type: "event",
		name: "Approval",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "owner",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "operator",
				type: "address",
				indexed: true,
			},
			{
				internalType: "bool",
				name: "approved",
				type: "bool",
				indexed: false,
			},
		],
		type: "event",
		name: "ApprovalForAll",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "string",
				name: "oldURI",
				type: "string",
				indexed: false,
			},
			{
				internalType: "string",
				name: "newURI",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "BaseURIUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "string",
				name: "oldURI",
				type: "string",
				indexed: false,
			},
			{
				internalType: "string",
				name: "newURI",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "CollectionImageURIUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "amount",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "FundsWithdrawn",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "oldMaxSupply",
				type: "uint256",
				indexed: false,
			},
			{
				internalType: "uint256",
				name: "newMaxSupply",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "MaxSupplyUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "oldPrice",
				type: "uint256",
				indexed: false,
			},
			{
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "MintPriceUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
			{
				internalType: "string",
				name: "paymentMethod",
				type: "string",
				indexed: false,
			},
		],
		type: "event",
		name: "Minted",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "oldToken",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "newToken",
				type: "address",
				indexed: true,
			},
		],
		type: "event",
		name: "PaymentTokenUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "oldPrice",
				type: "uint256",
				indexed: false,
			},
			{
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "TokenMintPriceUpdated",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "amount",
				type: "uint256",
				indexed: false,
			},
		],
		type: "event",
		name: "TokensWithdrawn",
		anonymous: false,
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "from",
				type: "address",
				indexed: true,
			},
			{
				internalType: "address",
				name: "to",
				type: "address",
				indexed: true,
			},
			{
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
				indexed: true,
			},
		],
		type: "event",
		name: "Transfer",
		anonymous: false,
	},
	{
		inputs: [
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "approve",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		stateMutability: "view",
		type: "function",
		name: "balanceOf",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "baseTokenURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "collectionImageURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "factory",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "getApproved",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "getCurrentSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "address", name: "operator", type: "address" },
		],
		stateMutability: "view",
		type: "function",
		name: "isApprovedForAll",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "maxSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "payable",
		type: "function",
		name: "mint",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "mintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "address", name: "to_", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "mintTo",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "nonpayable",
		type: "function",
		name: "mintWithToken",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "name",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "ownerOf",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "paymentToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "safeTransferFrom",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "bytes", name: "data", type: "bytes" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "safeTransferFrom",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "bool", name: "approved", type: "bool" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "setApprovalForAll",
	},
	{
		inputs: [{ internalType: "string", name: "newBaseURI_", type: "string" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setBaseURI",
	},
	{
		inputs: [{ internalType: "string", name: "newImageURI_", type: "string" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setCollectionImageURI",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "newMaxSupply_", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "setMaxSupply",
	},
	{
		inputs: [{ internalType: "uint256", name: "newPrice_", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setMintPrice",
	},
	{
		inputs: [{ internalType: "address", name: "newToken_", type: "address" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setPaymentToken",
	},
	{
		inputs: [{ internalType: "uint256", name: "newPrice_", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
		name: "setTokenMintPrice",
	},
	{
		inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
		stateMutability: "view",
		type: "function",
		name: "supportsInterface",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "symbol",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "tokenByIndex",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "tokenMintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "uint256", name: "index", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
		name: "tokenOfOwnerByIndex",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId_", type: "uint256" }],
		stateMutability: "view",
		type: "function",
		name: "tokenURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
	},
	{
		inputs: [],
		stateMutability: "view",
		type: "function",
		name: "totalSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "transferFrom",
	},
	{
		inputs: [
			{ internalType: "address payable", name: "to_", type: "address" },
			{ internalType: "uint256", name: "amount_", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "withdrawFunds",
	},
	{
		inputs: [
			{ internalType: "address", name: "to_", type: "address" },
			{ internalType: "uint256", name: "amount_", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "function",
		name: "withdrawTokens",
	},
	{ inputs: [], stateMutability: "payable", type: "receive" },
] as const;

export const STAR_OWNER = [
	{
		inputs: [
			{ internalType: "string", name: "name_", type: "string" },
			{ internalType: "string", name: "symbol_", type: "string" },
			{ internalType: "uint256", name: "mintPrice_", type: "uint256" },
			{ internalType: "uint256", name: "tokenMintPrice_", type: "uint256" },
			{ internalType: "address", name: "paymentToken_", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], name: "AccessControlBadConfirmation", type: "error" },
	{
		inputs: [
			{ internalType: "address", name: "account", type: "address" },
			{ internalType: "bytes32", name: "neededRole", type: "bytes32" },
		],
		name: "AccessControlUnauthorizedAccount",
		type: "error",
	},
	{ inputs: [], name: "AdminAlreadyExists", type: "error" },
	{ inputs: [], name: "AdminDoesNotExist", type: "error" },
	{ inputs: [], name: "AlreadyVoted", type: "error" },
	{ inputs: [], name: "ERC20PaymentNotEnabled", type: "error" },
	{
		inputs: [
			{ internalType: "address", name: "sender", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "address", name: "owner", type: "address" },
		],
		name: "ERC721IncorrectOwner",
		type: "error",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		name: "ERC721InsufficientApproval",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "approver", type: "address" }],
		name: "ERC721InvalidApprover",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "operator", type: "address" }],
		name: "ERC721InvalidOperator",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		name: "ERC721InvalidOwner",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "receiver", type: "address" }],
		name: "ERC721InvalidReceiver",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "sender", type: "address" }],
		name: "ERC721InvalidSender",
		type: "error",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		name: "ERC721NonexistentToken",
		type: "error",
	},
	{ inputs: [], name: "InsufficientBalance", type: "error" },
	{ inputs: [], name: "InvalidAddress", type: "error" },
	{ inputs: [], name: "InvalidParameters", type: "error" },
	{ inputs: [], name: "LastAdminCannotBeRemoved", type: "error" },
	{ inputs: [], name: "ProposalAlreadyExecuted", type: "error" },
	{ inputs: [], name: "ProposalExpired", type: "error" },
	{ inputs: [], name: "ProposalNotFound", type: "error" },
	{ inputs: [], name: "QuorumNotReached", type: "error" },
	{
		inputs: [{ internalType: "address", name: "token", type: "address" }],
		name: "SafeERC20FailedOperation",
		type: "error",
	},
	{ inputs: [], name: "TokenTransferFailed", type: "error" },
	{ inputs: [], name: "WithdrawalFailed", type: "error" },
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "admin",
				type: "address",
			},
		],
		name: "AdminAdded",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "admin",
				type: "address",
			},
		],
		name: "AdminRemoved",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "owner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "approved",
				type: "address",
			},
			{
				indexed: true,
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
			},
		],
		name: "Approval",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "owner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "operator",
				type: "address",
			},
			{ indexed: false, internalType: "bool", name: "approved", type: "bool" },
		],
		name: "ApprovalForAll",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "FundsWithdrawn",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "oldPrice",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
			},
		],
		name: "MintPriceUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "oldToken",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newToken",
				type: "address",
			},
		],
		name: "PaymentTokenUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "uint256",
				name: "proposalId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "enum StarOwner.ProposalType",
				name: "proposalType",
				type: "uint8",
			},
			{
				indexed: true,
				internalType: "address",
				name: "proposer",
				type: "address",
			},
		],
		name: "ProposalCreated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "uint256",
				name: "proposalId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "enum StarOwner.ProposalType",
				name: "proposalType",
				type: "uint8",
			},
		],
		name: "ProposalExecuted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "uint256",
				name: "proposalId",
				type: "uint256",
			},
			{
				indexed: true,
				internalType: "address",
				name: "voter",
				type: "address",
			},
		],
		name: "ProposalVoted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "newThreshold",
				type: "uint256",
			},
		],
		name: "QuorumUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
			{
				indexed: true,
				internalType: "bytes32",
				name: "previousAdminRole",
				type: "bytes32",
			},
			{
				indexed: true,
				internalType: "bytes32",
				name: "newAdminRole",
				type: "bytes32",
			},
		],
		name: "RoleAdminChanged",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
			{
				indexed: true,
				internalType: "address",
				name: "account",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "sender",
				type: "address",
			},
		],
		name: "RoleGranted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
			{
				indexed: true,
				internalType: "address",
				name: "account",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "sender",
				type: "address",
			},
		],
		name: "RoleRevoked",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "oldPrice",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
			},
		],
		name: "TokenMintPriceUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{
				indexed: true,
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "string",
				name: "paymentMethod",
				type: "string",
			},
		],
		name: "TokenMinted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "string",
				name: "newURI",
				type: "string",
			},
		],
		name: "TokenURIUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "TokensWithdrawn",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "from", type: "address" },
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{
				indexed: true,
				internalType: "uint256",
				name: "tokenId",
				type: "uint256",
			},
		],
		name: "Transfer",
		type: "event",
	},
	{
		inputs: [],
		name: "DEFAULT_ADMIN_ROLE",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		name: "approve",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		name: "balanceOf",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "admin_", type: "address" }],
		name: "createAddAdminProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "admin_", type: "address" }],
		name: "createRemoveAdminProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "newPrice_", type: "uint256" }],
		name: "createSetMintPriceProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newToken_", type: "address" }],
		name: "createSetPaymentTokenProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "newFee_", type: "uint256" }],
		name: "createSetTokenFeeProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "to_", type: "address" },
			{ internalType: "uint256", name: "amount_", type: "uint256" },
		],
		name: "createWithdrawFundsProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "to_", type: "address" },
			{ internalType: "uint256", name: "amount_", type: "uint256" },
		],
		name: "createWithdrawTokensProposal",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "getAdmins",
		outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		name: "getApproved",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "proposalId_", type: "uint256" }],
		name: "getProposalDetails",
		outputs: [
			{ internalType: "address", name: "proposer", type: "address" },
			{ internalType: "uint256", name: "createdAt", type: "uint256" },
			{ internalType: "uint256", name: "approvalCount", type: "uint256" },
			{ internalType: "uint256", name: "expirationTime", type: "uint256" },
			{ internalType: "bool", name: "executed", type: "bool" },
			{
				internalType: "enum StarOwner.ProposalType",
				name: "proposalType",
				type: "uint8",
			},
			{ internalType: "address", name: "targetAddress", type: "address" },
			{ internalType: "uint256", name: "value", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
		name: "getRoleAdmin",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getTotalProposals",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{ internalType: "address", name: "account", type: "address" },
		],
		name: "grantRole",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{ internalType: "address", name: "account", type: "address" },
		],
		name: "hasRole",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "proposalId_", type: "uint256" },
			{ internalType: "address", name: "admin_", type: "address" },
		],
		name: "hasVotedForProposal",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "address", name: "operator", type: "address" },
		],
		name: "isApprovedForAll",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "string", name: "ipfsURI_", type: "string" }],
		name: "mint",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "mintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "string", name: "ipfsURI_", type: "string" }],
		name: "mintWithToken",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "name",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
		name: "ownerOf",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "paymentToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "quorumThreshold",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{ internalType: "address", name: "callerConfirmation", type: "address" },
		],
		name: "renounceRole",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "role", type: "bytes32" },
			{ internalType: "address", name: "account", type: "address" },
		],
		name: "revokeRole",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		name: "safeTransferFrom",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "bytes", name: "data", type: "bytes" },
		],
		name: "safeTransferFrom",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "bool", name: "approved", type: "bool" },
		],
		name: "setApprovalForAll",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "bytes4", name: "interfaceId_", type: "bytes4" }],
		name: "supportsInterface",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "symbol",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "tokenMintPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenId_", type: "uint256" }],
		name: "tokenURI",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "totalSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
		],
		name: "transferFrom",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "tokenId_", type: "uint256" },
			{ internalType: "string", name: "newURI_", type: "string" },
		],
		name: "updateTokenURI",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "proposalId_", type: "uint256" }],
		name: "voteForProposal",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{ stateMutability: "payable", type: "receive" },
] as const;
